.TH "3Lab/ArgumentParser.h" 3 "Version 0.1" "Sound Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
3Lab/ArgumentParser.h \- Header file for the \fBArgumentParser\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <getopt\&.h>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArgumentParser\fP"
.br
.RI "Class \fBArgumentParser\fP provides a convenient interface for parsing command line arguments using the getopt_long(3) function\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header file for the \fBArgumentParser\fP class\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Sound Processor from the source code\&.
