.TH "3Lab/ArgumentParser.cpp" 3 "Version 0.1" "Sound Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
3Lab/ArgumentParser.cpp \- Implementation of the \fBArgumentParser\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <getopt\&.h>\fP
.br
\fR#include <string>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <stdexcept>\fP
.br
\fR#include 'ArgumentParser\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const std::string \fBkRED\fP = '\\033[1;31m'"
.br
.ti -1c
.RI "const std::string \fBkRESET\fP = '\\033[0m'"
.br
.ti -1c
.RI "const std::string \fBkYELLOW\fP = '\\033[33m'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation of the \fBArgumentParser\fP class\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Sound Processor from the source code\&.
