.TH "3Lab/ConfigParser.cpp" 3 "Version 0.1" "Sound Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
3Lab/ConfigParser.cpp \- Implementation of the \fBConfigParser\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <iostream>\fP
.br
\fR#include 'ConfigParser\&.h'\fP
.br
\fR#include 'Converter\&.h'\fP
.br
\fR#include 'Creators\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Implementation of the \fBConfigParser\fP class\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Sound Processor from the source code\&.
