.TH "3Lab/ConfigParser.h" 3 "Version 0.1" "Sound Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
3Lab/ConfigParser.h \- Header file for the \fBConfigParser\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <queue>\fP
.br
\fR#include <regex>\fP
.br
\fR#include 'Converter\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConfigParser\fP"
.br
.RI "Class \fBConfigParser\fP provides a convenient interface for parsing a configuration file using std::regex\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header file for the \fBConfigParser\fP class\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Sound Processor from the source code\&.
