.TH "3Lab/Converter.cpp" 3 "Version 0.1" "Sound Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
3Lab/Converter.cpp \- Implementation of the \fBConverter\fP class and its derived classes\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <algorithm>\fP
.br
\fR#include <string>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <filesystem>\fP
.br
\fR#include <cmath>\fP
.br
\fR#include 'Converter\&.h'\fP
.br
\fR#include 'WAVHeader\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Implementation of the \fBConverter\fP class and its derived classes\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Sound Processor from the source code\&.
