.TH "Creater" 3 "Version 0.1" "Sound Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Creater \- Base class for factory method\&. Base class for all creater classes\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Creators\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCreater\fP ()=default"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "virtual \fB~Creater\fP ()=default"
.br
.RI "Virtual destructor\&. "
.in -1c
.SH "Detailed Description"
.PP 
Base class for factory method\&. Base class for all creater classes\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Sound Processor from the source code\&.
