.TH "3Lab/Creators.h" 3 "Version 0.1" "Sound Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
3Lab/Creators.h \- This file contains the declaration of the \fBCreater\fP base class and its derived classes: \fBMuteCreater\fP, \fBMixCreater\fP, and \fBDistortionCreater\fP\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br
\fR#include 'Converter\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCreater\fP"
.br
.RI "Base class for factory method\&. Base class for all creater classes\&. "
.ti -1c
.RI "class \fBMuteCreater\fP"
.br
.RI "Class responsible for the creation of Mute \fBConverter\fP\&. "
.ti -1c
.RI "class \fBMixCreater\fP"
.br
.RI "Class responsible for the creation of Mix converters\&. "
.ti -1c
.RI "class \fBDistortionCreater\fP"
.br
.RI "Class responsible for the creation of Distortion \fBConverter\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
This file contains the declaration of the \fBCreater\fP base class and its derived classes: \fBMuteCreater\fP, \fBMixCreater\fP, and \fBDistortionCreater\fP\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Sound Processor from the source code\&.
