.TH "3Lab/Creators.cpp" 3 "Version 0.1" "Sound Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
3Lab/Creators.cpp \- Implementation of the creator classes for different converter types\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'Creators\&.h'\fP
.br
\fR#include 'Converter\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Implementation of the creator classes for different converter types\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Sound Processor from the source code\&.
