.TH "MuteOption" 3 "Version 0.1" "Sound Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MuteOption \- Class for muting a section of an audio file\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Converter\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMuteOption\fP (uint32_t left, uint32_t right)"
.br
.RI "Constructor for the \fBMuteOption\fP class\&. "
.ti -1c
.RI "void \fBConvert\fP (std::string input_file, std::string output_file) override"
.br
.RI "Applies the mute operation to the input file and saves the result to the output file\&. "
.ti -1c
.RI "void \fBhelp\fP () const override"
.br
.RI "Displays help information for the \fBMuteOption\fP converter\&. "
.in -1c

Public Member Functions inherited from \fBConverter\fP
.in +1c
.ti -1c
.RI "\fBConverter\fP ()=default"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "virtual \fB~Converter\fP ()=default"
.br
.RI "Default destructor\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class for muting a section of an audio file\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MuteOption::MuteOption (uint32_t left, uint32_t right)"

.PP
Constructor for the \fBMuteOption\fP class\&. 
.PP
\fBParameters\fP
.RS 4
\fIleft\fP The left boundary for the mute operation\&. 
.br
\fIright\fP The right boundary for the mute operation\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void MuteOption::Convert (std::string input_file, std::string output_file)\fR [override]\fP, \fR [virtual]\fP"

.PP
Applies the mute operation to the input file and saves the result to the output file\&. 
.PP
\fBParameters\fP
.RS 4
\fIinput_file\fP The input WAV file\&. 
.br
\fIoutput_file\fP The output WAV file\&. 
.RE
.PP

.PP
Implements \fBConverter\fP\&.
.SS "void MuteOption::help () const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Displays help information for the \fBMuteOption\fP converter\&. 
.PP
Implements \fBConverter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Sound Processor from the source code\&.
