.TH "SoundProcessor" 3 "Version 0.1" "Sound Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoundProcessor
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBControl\fP (int argc, char *argv[])"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Sound Processor from the source code\&.
