.TH "3Lab/WAVHeader.h" 3 "Version 0.1" "Sound Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
3Lab/WAVHeader.h \- Header file defining the structure of a WAV file header\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <cstdint>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBWAVHeader\fP"
.br
.RI "A structure representing the header of a WAV file\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFIXED_SAMPLE_RATE\fP   44100"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header file defining the structure of a WAV file header\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Sound Processor from the source code\&.
